version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
    db:
      platform: linux/x86_64
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3307:3306'
      expose:
         - '3306'
      volumes:
        - my-db:/var/lib/mysql
volumes:
 my-db: