version: "3.8"

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
    db:
      container_name: db
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '3309:3306'
      expose:
         - '3306'
      volumes:
        - my-db:/var/lib/mysql

    server:
        container_name: eureka-server
        build: ./server
        ports: 
          - 8083:8083
        networks:
            - spring-cloud-network

    gateway:
        container_name: eureka-gateway
        build: ./gateway
        ports: 
          - 8084:8084
        depends_on:
          - server
        networks:
            - spring-cloud-network
        environment:
          - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka

    endereco-ms:
        container_name: eureka-enderecos
        build: ./endereco-ms
        depends_on:
          - gateway
        networks:
            - spring-cloud-network
        environment:
          - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka
          - SPRING_DATASOURCE_URL=jdbc:mysql://10.102.17.86:3309/enderecos?createDatabaseIfNotExist=true
          - SPRING_DATASOURCE_PASSWORD=password

    medico-ms:
        container_name: eureka-medicos
        build: ./medico-ms
        depends_on:
          - gateway
          - endereco-ms
        networks:
            - spring-cloud-network
        environment:
          - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka
          - SPRING_DATASOURCE_URL=jdbc:mysql://10.102.17.86:3309/medicos?createDatabaseIfNotExist=true
          - SPRING_DATASOURCE_PASSWORD=password

    paciente-ms:
        container_name: eureka-pacientes
        build: ./paciente-ms
        depends_on:
          - gateway
          - endereco-ms
        networks:
            - spring-cloud-network
        environment:
          - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka
          - SPRING_DATASOURCE_URL=jdbc:mysql://10.102.17.86:3309/pacientes?createDatabaseIfNotExist=true
          - SPRING_DATASOURCE_PASSWORD=password

    consulta-ms:
        container_name: eureka-consultas
        build: ./consulta-ms
        depends_on:
          - gateway
        networks:
            - spring-cloud-network
        environment:
          - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka
          - SPRING_DATASOURCE_URL=jdbc:mysql://10.102.17.86:3309/consultas?createDatabaseIfNotExist=true
          - SPRING_DATASOURCE_PASSWORD=password
          - SPRING_RABBITMQ_HOST=10.102.17.86

    email-ms:
        container_name: emails
        build: ./email-ms/email
        depends_on:
          - rabbitmq
        networks:
            - spring-cloud-network
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://10.102.17.86:3309/emails?createDatabaseIfNotExist=true
          - SPRING_DATASOURCE_PASSWORD=password
          - SPRING_MAIL_USERNAME=qastudent.trilhas@gmail.com
          - SPRING_MAIL_PASSWORD=fdndhmlobajbmktw
          - SPRING_RABBITMQ_HOST=10.102.17.86

volumes:
 my-db:

networks:
    spring-cloud-network:
        driver: bridge