version: '3.8'

services:
    server:
        container_name: eureka-server
        build: ./server
        ports: 
          - 8083:8083
        networks:
            - spring-cloud-network

    gateway:
        container_name: eureka-gateway
        build: ./gateway
        ports: 
          - 8084:8084
        depends_on:
          - server
        networks:
            - spring-cloud-network
        environment:
          - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka

    endereco-ms:
        container_name: eureka-enderecos
        build: ./endereco-ms
        depends_on:
          - gateway
        networks:
            - spring-cloud-network
        environment:
          - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8083/eureka
          - SPRING_DATASOURCE_URL=jdbc:mysql://db:3309/enderecos?createDatabaseIfNotExist=true
networks:
    spring-cloud-network:
        driver: bridge