version: '3.8'
services:
    server:
        container_name: eureka-server
        build: ./server
        ports: 
          - 8083:8083
        networks:
            - spring-cloud-network
    gateway:
        container_name: eureka-gateway
        build: ./gateway
        ports: 
          - 8084:8084
        depends_on:
          - server
        networks:
            - spring-cloud-network
        environment:
          SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8083/eureka"}}}}'
    endereco-ms:
        container_name: eureka-enderecos
        build: ./endereco-ms
        depends_on:
          - gateway
        networks:
            - spring-cloud-network
        environment:
          SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8083/eureka"}}}}'
networks:
    spring-cloud-network:
        driver: bridge